- CHANGELOG.md
- packages/system/src/components/homepage/latest-tools.tsx
Fixed the resource to which the "View all tools" link on the home page should lead. Changed `"/categories/blogs"` to `"/categories/tools"`
> fix the resource to which the "View all tools" link should lead

- CHANGELOG.md
- packages/system/src/components/homepage/hero.css.ts
- packages/system/src/components/homepage/hero.tsx
Added missing drop shadows to the feature highlight images
> Add drop shadow to feature highlights on homepage

- CHANGELOG.md
- packages/system/src/components/homepage/homepage.css.ts
Added bottom padding to the `homepageContentContainerStyle` which currently only had top padding. This resulted in the content being flush with the window at the bottom.
> add padding to bottom of home page so it's not flush with window

- packages/system/src/components/cards/resource-card.css.ts
added a `maxHeight` to `resourceCardImageStyle` to keep the cards more consistently laid out
> set a `maxHeight` on `resourceCardImageStyle`

- CHANGELOG.md
- amplify.yml
- packages/angular/README.md
- packages/vue/README.md
Adding vue/angular folders for the deployments of both angular.framework.dev and vue.framework.dev, plus adding amplify config for the landing site
> Feature: add amplify config for landing site and angular/vue sites

- CHANGELOG.md
- packages/system/src/components/homepage/hero.css.ts
- packages/system/src/components/homepage/hero.tsx
- packages/system/src/components/logo.tsx
Updated header text with new content as per #189. Also highlight boxes have been updated to links. A "." character has also been added in between the site type and framework.dev in the logo.
> feat: added links to home page highlights and updated header text

- packages/landing-site/src/constants/index.ts
- packages/system/src/components/cards/resource-card.css.ts
- packages/system/src/components/landing/hero.tsx
- packages/system/src/components/landing/link-card-group.tsx
- packages/system/src/components/landing/resources-info-banner.tsx
Fixed the landing page resources cards where they weren't having different height sizes as shown in the figma, fixed as well the communities cards styles that were looking uneven from each other
> Style: fix both communities cards and link cards styles

- packages/site/src/data/vue/libraries.ts
Adds the Harlem library to the list of Vue libraries.
Adds the Harlem state management library for Vue 3 to the list of libraries.
and unique
Wasn't requested, but here's a screenshot of the new card:
> Add Harlem to list of Vue libraries

- .github/pull_request_template.md
PR templates utilize the relative path to the CONTRIBUTING.md but the GitHub PR flow doesn't resolve them correctly. This updates those links to be absolute URLs.
- ~[ ] This fix resolves #~
> fix: update contributing guidelines link to be absolute instead of relative

- packages/system/src/components/comparison-table/index.tsx
- packages/system/src/components/skeleton.css.ts
- packages/system/src/components/skeleton.stories.tsx
- packages/system/src/components/skeleton.tsx
Improve feedback for the user in the comparison table adding an skeleton loader
> Feat: improve feedback for user

- packages/system/src/components/comparison-table/index.tsx
- packages/system/src/components/comparison-table/utils.ts
Fix value shown in the table when error in the API occurs
> fix: show correct value in comparison table

- packages/system/src/components/comparison-table/utils.ts
Fix sorting in comparison table that was case sensitive.
> Fix: sorting in comparison table

- packages/system/src/components/comparison-table/utils.ts
When the elements where sorting, it wasn't changing the reference of the array hence not triggering a re-render - Fixed
> Fix: comparison table remove button stopped working

- packages/landing-site/src/layouts/base.astro
- packages/site/src/layouts/base.astro
Lifted the Google Tag Manager key to an env var stored in AWS at `SNOWPACK_PUBLIC_GOOGLE_ANALYTICS`.
> updated analytics key to env var

- packages/landing-site/src/layouts/base.astro
- packages/site/src/layouts/base.astro
Adds a fallback to the configure google analytics env var locally.
> added env var fallback

- packages/landing-site/src/layouts/base.astro
- packages/site/src/layouts/base.astro
- Reverts adding a fallback to google analytics as each site's analytics ID is dynamically added and never the same
- Limits the google analytics to only setup in prod
> limited google analytics to prod

- packages/landing-site/src/layouts/base.astro
- packages/site/src/layouts/base.astro
Resolves a rendering issue in prod that wasn't visible locally by correcting how the conditional script tags appear.
> fixed script rendering for analytics

- packages/site/src/data/solidjs/blogs.ts
Closes #296
There are currently only two blogs dedicated to solidjs and they belong to the libraries' author, the other blogs i could find had maybe just one or two articles on solidjs, added the one i could find.
> Add blogs content for framework

- packages/site/src/data/solidjs/libraries.ts
Added contents for libraries related to Solidjs and ensured they showed on the site
As a visitor of the framework specific Framework.dev site I would like to have the ability to see enough Libraries content to keep me informed and find this site to be resourceful and useful.
Libraries have to be split into
- State management
- Data Fetching
- Styling
- Component Library
- Form
- Framework
- Internationalization
> chore: contents added

- packages/site/src/data/vue/podcasts.ts
closes #351 
An image has been successfully displayed -
>   Added Logo Views on Vue

- packages/site/src/data/angular/blogs.ts
- packages/site/src/data/angular/courses.ts
- packages/site/src/data/angular/libraries.ts
- packages/site/src/data/react/blogs.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/react/courses.ts
- packages/site/src/data/react/libraries.ts
- packages/site/src/data/vue/blogs.ts
- packages/site/src/data/vue/courses.ts
- packages/site/src/data/vue/libraries.ts
This PR is ensuring that all of This Dot Labs content has been added to the React, Vue and Angular sites. 
closes #347 
and unique
> feat: adding this dot content to all framework sites

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/vue/communities.ts
> remove unrelated conferences and fix naming

- packages/site/src/data/react/libraries.ts
> fix framer motion logo

- packages/site/src/data/vue/libraries.ts
Keen UI logo missing fixes #363
Keen UI logo was missing from libraries.ts in vue
> Keen UI logo missing fixes #363

- packages/site/src/data/graphql/podcasts.ts
**_Before_**
**_After_**
and unique
> feat: adds graphql content for podcasts

- packages/site/src/layouts/base.astro
While testing the social share cards, I noticed that the homepage was showing up undefined in the card description. I put in a fix to show the current category if there is one, otherwise show the main title. 
I have also tested all of the subpages on [Social Share](https://socialsharepreview.com/) and they are working fine.
closes #419
and unique
> fix: undefined for social share cards homepage

- packages/site/src/data/graphql/blogs.ts
I have added all of the blog content from this google doc
https://docs.google.com/spreadsheets/d/1KQ-16uyfH8XG1_Xjt4UuG0KvrlH6SrWDx5mKPLihEA8/edit#gid=0
and unique
closes #421
> feat: adding blog content for graphql site

- packages/system/src/themes/graphql-color-scheme.ts
This PR is responsible for changing the logo color in the `graphqlColorPalette` to the primary color listed in the figma files.
closes #432 
Here is the figma file for all of the primary colors for the frameworks
https://www.figma.com/file/3cAQKdlEpCrz7dgeKzJEqQ/Framework-library?node-id=5%3A2
and unique
> fix: setting graphql logo to primary color

- packages/site/src/components/social-meta-tags.tsx
- packages/site/src/pages/index.astro
- packages/system/src/components/homepage/hero.tsx
- packages/system/src/util/string-utils.ts
Currently on the homepage site, the name displays Graphql which is incorrect.
I created a function in the `string-utils` file that only capitalizes the first letter for all other frameworks except GraphQL. 
I also changed the name for the social cards.
closes #438 
and unique
> fixing site name so it displays GraphQL on homepage and social cards

- packages/site/src/components/social-meta-tags.tsx
This PR fixes the incorrect spelling for GraphQL in the social cards. 
closes #455 
and unique
> fix: GraphQL name in social card

- packages/system/src/components/homepage/books.tsx
View all books now properly directs to books
> fix: view all books href

- packages/site/src/data/search-data.ts
Make the `Libraries` nav items to be dynamic to the tags
**_Before_**
**_After_**
> refactor: makes the libary nav dynamic

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/vue/communities.ts
- packages/system/src/components/cards/community-card.tsx
- packages/system/src/components/cards/resource-card.tsx
- packages/system/src/models/community.ts
Currently images with a transparent background that require a dark background are illegible. This PR provides a solution to address this issue (and future transparent images) by adding `darkImageBackground` with a boolean value to community resources that require it.
Before:
After:
closes #368
> fix(#368): add support for dark background on transparent images

- packages/site/src/data/graphql/podcasts.ts
Replacing broken image for podcast
> fix: broken GraphQL podcast image

- packages/site/src/data/vue/libraries.ts
Chakra UI logo is missing from the Vue framework.dev page. PR provides current logo from Chakra UI GitHub.
> fix(#364): add missing chakra ui logo

- package.json
- packages/site/snowpack.config.js
Cleared the "DialogContent" error from the CLI by updating `@reach/dialog` and updating `snowpack.config.js`. The `innerHTML` error is generated from build in Snowpack and should be resolved once we migrate to Vite.
Before:
----------
After:
> chore(#252): update reach dialog and config due to cli errors

- packages/system/src/components/homepage/contributor-banner.tsx
I fixed the spelling error that was in the banner component. This banner component is used in all framework.dev sites. 
closes #529 
and unique
> fixing spelling error in banner component

- packages/site/src/components/social-meta-tags.tsx
- packages/site/src/pages/index.astro
- packages/system/src/components/homepage/hero.tsx
- packages/system/src/util/string-utils.ts
- Change the label when we are showing the SolidJS Framework.dev page
Closes: #535
> feat(SolidJS): Fix misspelled labels

- packages/site/src/data/qwik/tools.ts
Close: https://github.com/thisdot/framework.dev/issues/546
Removed graphql tools in the qwik tools that don't make below
and unique
> Remove GraphQL Tools From Qwik Tools

- packages/system/src/components/cards/library-card.tsx
- packages/system/src/components/cards/resource-card.tsx
Deno does not have a centralized repository of packages. There are some hosting services, like deno.land/x, but they don't expose package stats easily, developers are not required to use this hosting service. They can fetch modules from anywhere, even directly from GitHub.
Therefore we've decided to disable the comparison feature for Deno:
> Disable selection for Deno

- packages/system/src/components/comparison-table/index.tsx
The npms.io API to fetch comparison table stats expects the package name, not the full NPM URL. This fix checks if the library package value contains the URL, and strips it out if it does.
> Fix comparison table not showing full npm stats

- packages/site/src/data/deno/libraries.ts
- packages/site/src/data/search-data.ts
This just renames "Drivers" to "Database Drivers" as suggested by Dustin.
> Rename Drivers to Database Drivers

- packages/landing-site/src/components/contributor-banner.tsx
- packages/landing-site/src/components/resources-info-banner.tsx
- packages/landing-site/src/layouts/base.astro
- packages/site/src/pages/index.astro
- packages/system/src/components/homepage/contributor-banner.css.ts
- packages/system/src/components/homepage/contributor-banner.stories.tsx
- packages/system/src/components/homepage/contributor-banner.tsx
- packages/system/src/components/homepage/contributor.css.ts
- packages/system/src/components/homepage/contributor.stories.tsx
- packages/system/src/components/homepage/contributor.tsx
- packages/system/src/components/homepage/homepage.tsx
- packages/system/src/github-util/get-contributors.ts
* make left column text top-aligned
* change left column copy
* unify spacing between contributors' avatars
* add alt text to avatar images (user login)
* link contributor's avatar the GitHub profile page (open in new tab)
* change yellow background to transparent
* add contributors banner to landing page
* fix ContributorBanner story
* add Contributor story
* modified landing page margins for the new section
> feat: 574 contributors banner improvements

- README.md
- packages/system/src/components/comparison-table/index.tsx
The npms.io API to fetch comparison table stats return the package name, not the full NPM URL. This fix parses the libraries array and transform the package value to only be the name we need.
Also fixed a typo in the README.md file.
> Fix: comparison table not showing stats correctly

- packages/site/src/data/svelte/libraries.ts
> [svelte-kit-scss] Hide State Management from Libraries if we don't have content

- CONTRIBUTING.md
- build-ignore.js
- packages/landing-site/src/layouts/base.astro
- packages/site/package.json
- packages/site/src/layouts/base.astro
- packages/site/src/pages/categories/[category]/index.astro
- packages/site/src/pages/categories/[category]/tags/[tag].astro
- packages/site/src/pages/index.astro
- packages/site/src/pages/search.astro
- packages/system/src/components/button.tsx
- packages/system/src/components/chip.tsx
- packages/system/src/components/search/query-util.ts
As part of updating the site to Astro v1, the environment variable the `build-ignore` script was using was changed. This updates the script to use the new variable name, as well as adding a check for any config files to the site so those will cause new builds as well. 
I also updated a line in the CONTRIBUTING markdown file so it no longer tells users to look in a folder that doesn't exist for where to find tag information.
For reference - the environment variable the script matches on has already been changed on all of the Netlify sites:
**EDIT Jan 10**: This ended up a bit more complex than initially thought. There's a few different things adjusted here so that the sites build properly:
- Initial fix is still correct. There's a small update to the CONTRIBUTING file, and the adjustments …
> Fix: netlify build updates

- packages/system/src/components/landing/link-card.css.ts
I didn't see any tools for handling class specificity in the docs look like it might just end up being dependent on the order things are bundled by the build system. So I went with a good old fashioned !important to fix the issue for now 
Specificity Issue
Before
After adding !important
> fix: Landing page link icons size

- packages/site/src/data/react/podcasts.ts
Changed the image for The React Native Podcast podcast item.
> updated the react native podcast image

- packages/site/src/data/deno/blogs.ts
- packages/site/src/data/deno/courses.ts
- packages/site/src/data/react/courses.ts
- packages/site/src/data/svelte/blogs.ts
- packages/system/src/util/example-content.ts
This is a content change to give freeCodeCamp naming consistent and correct convention
Closes #531 
and unique
> fix: unify freeCodeCamp naming conventions

- packages/site/src/data/vue/communities.ts
- packages/site/src/data/vue/podcasts.ts
Sorts resources for so React-specific titles appear ahead of This Dot branded titles.
> sorted vue communities

- package.json
- packages/system/src/github-util/get-contributors.ts
- yarn.lock
- Adds retry support to getContributorsData api request
There is an issue where periodically and not infrequently the getContributorsData api request fails when building the framework.dev sites. This leads to a failed build or a contributors section without a list of contributors (depending on whether or not you swallow the error) 
This PR adds retries to the request so that it will try to make the request 3 times before giving up and killing the build
Closes #690
> feat: add retries to getContributorsData to handle periodic failures

- packages/system/src/github-util/get-contributors.ts
Public API calls to the GitHub API get aggressively rate limited. This PR adds a PAT to the builds to authenticate the GH api requests to avoid being rate limited, triggering failures, while the sites are building.
I created a fine grained access token with no permissions on my personal account to accomplish this. This seems like the ideal route over a legacy PAT for security reasons. Fine grained PAT's need to be refreshed every few months though it appears. Will probably one to generate one from the labs github account for this.
> fix: Attempt to fix contributors list fetching

- packages/system/src/components/cards/card-layouts.css.ts
This PR sets the max width of a resource card on desktop size screens to half the available free space. In practice this just limits single cards on wide screens from only take 1/2 the space as if there were 2 cols set.
Screenshot examples:
> feat: Resource Card Max Width

- packages/site/src/data/vue/communities.ts
- Replaces broken Digital Ocean image with a new one
> fix: replace broken Digital Ocean image

- README.md
- packages/system/src/github-util/get-contributors.ts
This resolved the issues of the failing contributor message in local development. Now we are only use the authorization header when in production.
> fix: applying header authorization when in prod

- packages/site/src/data/vue/libraries.ts
closes #715 
I found a few broken images in the libraries section in the Vue site. I also found a broken link and fixed that too. 
- fixed broken link for Equal UI
- fixed broken image for Equal UI
- fixed broken image for PrimeVue
- fixed broken image for Naive Ui
> fix: replacing broken vue images

- packages/site/src/data/angular/courses.ts
Replace with a better resolution version of the image
Closes #713
> fix: Improved Decoded Frontend Logo Image

- packages/system/src/components/landing/resources-info-banner.tsx
Update the ResourceInfoBanner heading to be an h2 tag. Checked around and it doesn't really effect anything else. Cleared up the noted issue from lighthouse report
Closes #710
> fix: Change heading type for landing page resource cards

- packages/system/src/components/homepage/communities.tsx
- packages/system/src/components/homepage/content-banner.tsx
Updates communities section heading from "Get smarter on the go" to "Discover new communities"
Closes #714
> feat: new communities heading

- packages/site/src/data/solidjs/tools.ts
Improved logo images for items in the tools section. Items that did not have any quality logos or icons are set to use the Solid logo by default.
Closes #718
> fix: Solid tools logo images

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/deno/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/vue/communities.ts
Updates with the url to the logos hosted on their GitHub repositories.
Closes #712
> fix: Broken DevTernity Images

- packages/site/src/data/svelte/tools.ts
JetBrains IDE
Closes https://github.com/thisdot/framework.dev/issues/722
Replaced image property for **Svetle REPL**and **Svelte for JetBrains IDEs** with the image from **Svelte for VS Code**
> fix(svelte): replace cut off svelte icons in tools

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/deno/communities.ts
- packages/site/src/data/graphql/communities.ts
- packages/site/src/data/nodejs/communities.ts
- packages/site/src/data/qwik/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/solidjs/communities.ts
- packages/site/src/data/svelte/communities.ts
- packages/site/src/data/vue/communities.ts
Fixes broken JSConf chile logos across the site
Closes #725
> fix: JSConf Chile logos

- packages/site/src/data/deno/courses.ts
Fixes broken images on deno site
- fresh logos
- freeCodeCamp logo 
Closes #725
> fix: Deno site broken images

- packages/site/src/data/graphql/courses.ts
- packages/site/src/data/graphql/libraries.ts
- packages/site/src/data/graphql/tools.ts
Adds fixed logo images for missing or broken items on the GraphQL site
- wundergraph
- wp-graphql
- appsync
- graphql-eslint
Closes #719
> fix: GraphQL site logo images

- .vscode/settings.json
- packages/site/src/data/solidjs/libraries.ts
- Items are able to have multiple tags, and Solid Router should show under the Routing tag on framework.dev
> Added solidjs router resource

- .github/workflows/slack-notifications.yml
This PR is responsible for adding a slack notification when a PR is merged. I tested this with my personal slack setup. 
closes #768
> chore: adding slack notifications GH action

- packages/site/src/data/vue/books.ts
> fix: vue-the-road-to-enterprise cover image broken

- packages/site/src/data/solidjs/podcasts.ts
- On the podcast page for SolidJS, the tag reads "Solidjs", but should read, "SolidJS". 
- The tags on the SolidJS site reads, "SolidJS".
> solidjs to SolidJs

- packages/site/src/data/graphql/courses.ts
With respect to the GraphQL DataLoader JS marathon course:
> fix: Broken link, wrong image for graphql course

- packages/system/src/components/cards/library-card.css.ts
- packages/system/src/components/cards/library-card.tsx
- packages/system/src/components/cards/resource-card.css.ts
- packages/system/src/components/cards/resource-card.tsx
- packages/system/src/util/example-content.ts
Where a package isn't hosted on NPM, the existing fallback is an unstyled link. It doesn't fit with the styles of any of the other badges in library cards and its purpose is visually confusing. This PR implements a new fallback with styles that better match existing badges.
> New styles for links to non-NPM packages

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/deno/communities.ts
- packages/site/src/data/graphql/communities.ts
- packages/site/src/data/nodejs/communities.ts
- packages/site/src/data/qwik/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/solidjs/communities.ts
- packages/site/src/data/solidjs/libraries.ts
- packages/site/src/data/svelte/blogs.ts
- packages/site/src/data/svelte/communities.ts
- packages/site/src/data/vue/communities.ts
- packages/system/src/components/homepage/homepage.tsx
Hide books section on home page since books are empty
- Books has a big featured section on the homepage but SolidJS doesn't have any. We should probably consider a change to not make books so heavily featured and switch some homepage items around. Not a blocker but noting here.
> Hide books section on home page since books are empty

- packages/site/src/data/svelte/books.ts
Add a new svelte book "real-world svelte" https://www.amazon.com/Real-World-Svelte-Supercharge-mastering-development-ebook/dp/B0CG1HQK19
and unique
> feat: add real world svelte
