thisdot/framework.dev

- CHANGELOG.md
- packages/system/src/components/homepage/feature-and-list.css.ts
- packages/system/src/globals/vanilla-global.css.ts
Fixes two display bugs that appeared in iOS Safari
> Fix styling issues with iOS Safari

- CHANGELOG.md
- packages/site/src/data/react/libraries.ts
This adds Redux Toolkit, RTK Query, Jotai and Valtio to the libraries.
and unique
> add Redux Toolkit, RTK Query, Jotai, Valtio

- CHANGELOG.md
- packages/site/src/data/angular/blogs.ts
- packages/site/src/data/angular/books.ts
- packages/site/src/data/angular/communities.ts
- packages/site/src/data/angular/courses.ts
- packages/site/src/data/angular/libraries.ts
- packages/site/src/data/angular/tools.ts
Added new content for Angular that's been helpful to me or recommended.
- 3 blogs
- 1 book
- 2 communities
- 1 library
- 1 course
- 1 tool
and unique
> Angular content additions

- CHANGELOG.md
- packages/site/src/data/vue/podcasts.ts
Added some popular VueJS podcasts.
These changes can be previewed through [localhost:3000/categories/podcasts](http://localhost:3000/categories/podcasts)
and unique
> [Podcasts] Added first set of podcasts

- CHANGELOG.md
- packages/site/src/data/vue/blogs.ts
- packages/site/src/data/vue/books.ts
- packages/site/src/data/vue/communities.ts
- packages/site/src/data/vue/courses.ts
- packages/site/src/data/vue/tools.ts
Adding initial content for blogs, books, communities, courses and tools
and unique
> Vue - Feature: add new content for vue site

- CHANGELOG.md
- amplify.yml
Fixing amplify script for the landing
> Fix: amplify landing script base directory

- packages/site/src/layouts/base.astro
- packages/site/src/pages/index.astro
- packages/system/src/components/homepage/featured-libraries.tsx
- packages/system/src/components/homepage/homepage.tsx
Adding dynamic variations for the main site
> Fix: add more variations for the main site

- packages/site/src/data/vue/books.ts
- packages/site/src/data/vue/courses.ts
- packages/site/src/data/vue/libraries.ts
Added initial batch of VueJS libraries
and unique
> Vue - Added initial set of VueJS libraries

- packages/system/src/components/landing/footer.tsx
- packages/system/src/components/landing/link-card.tsx
- packages/system/src/components/mobile-nav.tsx
- packages/system/src/components/sidebar.tsx
Homepage links need to open in new tabs
> Fix: anchor link tags not opening new tabs

- packages/system/src/components/landing/link-card.css.ts
Fixing link cards height to resemble the figma design
> Fix link cards height

- packages/system/src/components/cards/resource-card.tsx
- packages/system/src/components/comparison-table/comparison-table.css.ts
- packages/system/src/components/comparison-table/components/cells.css.ts
- packages/system/src/components/comparison-table/components/cells.tsx
- packages/system/src/components/comparison-table/index.tsx
- packages/system/src/components/tooltip.css.ts
This PR addresses #190. The table's new column for the remove button is wide, but would require significant refactoring for that singular column I believe to bring it down to fit to the content as the entire table layout is set via `display: grid` and `display: contents` (although I'm not 100% sure).
Additionally, the issue of the compare add/remove buttons firing twice has been fixed by implementing `stopPropagation()` into the `onChange` actions.
Tooltip styling was also updated as a part of this, giving it a proper `zIndex` so that it doesn't get overlapped by other elements.
and unique
> feat: add remove button to comparison table

- packages/site/src/data/vue/tools.ts
Removing repeated resource in the tools of vue
and unique
> Fix: remove repeated tool resource

- packages/site/src/data/react/courses.ts
Build a Full-Stack App with Next.js, Supabase & Prisma
- [ x] Content addition
Added new React course; Build a Full-Stack App with Next.js, Supabase & Prisma
- [ x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [x ] I have searched all existing content and verified my additions are novel
and unique
- [ x] The content was added to the end of the appropriate data list
- [ x] All required content fields are accurately populated
- [ x] All items are tagged with all relevant tags
> content: Add new React course

- packages/site/src/data/react/libraries.ts
Add React Testing Library to list of React Libraries
and unique
> content: add react-testing-library

- packages/site/src/data/react/libraries.ts
> Update broken logo of react-query

- packages/site/src/data/angular/libraries.ts
- packages/site/src/data/react/libraries.ts
- packages/site/src/data/vue/libraries.ts
Added testing libraries for Vue, Angular and React.
and unique
> Feat: add testing libraries

- packages/site/src/data/react/libraries.ts
This pull request closes #253 by editing links.
> fix(libraries): zustand links

- packages/site/src/data/react/books.ts
- packages/site/src/data/react/courses.ts
- packages/site/src/data/react/podcasts.ts
- packages/site/src/data/react/tools.ts
This pull request closes #254 by fixing image's urls.
> fix(resources): images not showing

- amplify.yml
- packages/qwik/README.md
Configure amplify.yml file for qwik deployment
> Configure amplify.yml file for qwik deployment

- packages/site/src/data/qwik/tools.ts
> feat: add Tools for Qwik framework

- packages/site/src/components/social-meta-tags.tsx
- packages/site/src/data/qwik/communities.ts
Added Discord community, Reddit community and Github Discussions community.
Closes #283 
and unique
> Added 3 content for Qwik Communities

- packages/site/src/data/svelte/communities.ts
> feat(svelte): Curate svelte communities

- packages/site/src/data/svelte/courses.ts
> feat(svelte): Curate svelte courses

- packages/site/src/data/descriptions.ts
Closes #270 
Add a general social meta tags for frameworks.
> [solidjs-pod] 2. Add social image and description

- packages/system/src/globals/global-constants.tsx
- packages/system/src/icons/qwik-icon.tsx
> Add framework on the main framework.dev site banner

- packages/site/src/data/svelte/books.ts
> feat(svelte): Curate svelte books

- packages/site/src/data/solidjs/podcasts.ts
Closes #293 
Add podcast resources for solidjs on framework
> [solidjs-pod] Add content for Podcasts

- packages/site/src/data/qwik/podcasts.ts
> feat(Qwik): Add content for podcasts

- packages/site/src/data/solidjs/tools.ts
Closes #291 
Added alot of solidjs specific tools
> [solidjs-pod] Add content for Tools

- packages/site/src/data/qwik/libraries.ts
> feat(Qwik): Add content for libraries

- amplify.yml
- packages/solidjs/README.md
Closes #272 
Add SolidJS framework to amplify
Needed:
> [solidjs-pod] 3. Add solidjs to amplify

- packages/site/src/data/react/blogs.ts
> add TkDodo blog

- packages/system/src/globals/global-constants.tsx
- packages/system/src/icons/solidjs-icon.tsx
Add SolidJS to main site banner
and also a solidjs svg icon
Closes #274
> [solidjs-pod] 4. Add framework on main site banner

- packages/system/src/components/homepage/hero.tsx
Fixes a minor typo in the hero banner for all sites.
> updated copy for framework landing pages

- packages/system/src/components/homepage/hero-images.ts
Simplifies logic for loading hero banner images based on the selected framework.
> simplified hero image loading

- packages/site/src/data/nodejs/blogs.ts
> added nodejs framework blog content

- amplify.yml
I added node.js to the `amplify.yml`file. 
> chore: add nodejs to amplify

- amplify.yml
> adding amplify for nodejs

- amplify.yml
I have added graphql to the amplify.yml file
This addresses the first part of issue #419 
and unique
> adding graphql to the amplify.yml file

- packages/site/src/data/graphql/books.ts
> feat: adds graphql content for books

- packages/site/src/data/graphql/communities.ts
**_Before_**
**_Home_**
**_Meetups_**
**_Conferences_**
**_After_**
**_Home_**
**_Meetups_**
**_Conferences_**
and unique
> feat: adds graphql content for communities

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/vue/communities.ts
- packages/system/src/components/homepage/content-banner.tsx
While testing, I have sound a few broken or low quality images that needed to be replaced. 
| Before                                                                                                                                                                    | After                                                                                                                                                                     |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <img …
> fix: replacing low quality images 

- packages/site/src/data/graphql/communities.ts
- packages/site/src/data/graphql/podcasts.ts
- packages/site/src/data/graphql/tools.ts
Updates some of the communities, tools, and podcasts images to look better on the homepage
**_Before_**
**_Communities_**
**_Podcasts_**
**_Tools_**
**_After_**
**_Communities_**
**_Podcasts_**
**_Tools_**
> fix: updates graphql images to be homepage size friendly

- packages/site/src/data/qwik/tools.ts
- packages/site/src/data/react/tools.ts
- packages/site/src/data/solidjs/tools.ts
- packages/site/src/data/svelte/tools.ts
- packages/site/src/data/vue/tools.ts
> Added tanstack to tools in all framework

- packages/site/src/data/qwik/courses.ts
- Added courses content for Qwik page
> feat(qwik): Add content for courses

- packages/site/src/data/angular/blogs.ts
PR closes #458 
Adding ng-journal resource to blog section for Angular site.
and unique
> feat(#458): add resource to angular blogs

- packages/system/src/components/homepage/contributor-banner.tsx
Minor update to contributor banner wording.
> fix(#457): update wording in contributor banner

- packages/site/src/data/angular/communities.ts
Update an unsecured image to its secure equivalent.
> updated unsecure image

- packages/site/src/data/deno/books.ts
> [deno] add content for books

- packages/site/src/data/deno/communities.ts
> (deno) add communities

- packages/site/src/data/deno/podcasts.ts
> [deno] add podcasts

- packages/site/src/data/deno/tools.ts
> [deno] add tools

- packages/site/src/data/deno/courses.ts
> [Deno] Add content for courses

- packages/site/src/data/svelte/blogs.ts
Added svelte blogs:
https://joyofcode.xyz/categories/svelte
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started
https://www.freecodecamp.org/news/search?query=svelte
https://dev.to/t/svelte
https://dev.to/t/sveltekit
https://sveltesociety.dev/recipes
https://svelte.school/tutorials
https://dev.to/theether0
https://dev.to/askrodney
https://rodneylab.com/tags/sveltekit/
https://github.com/TheComputerM/awesome-svelte#official-resources
https://medium.com/tag/sveltekit
https://medium.com/tag/svelte
https://www.ryanfiller.com/
https://svelte.news/
https://svelte.deepwebworks.com/
and unique …
> [sveltekit-pod] Add content for Blog

- packages/site/src/data/svelte/podcasts.ts
Added podcasts: 
https://www.htmlallthethings.com/podcasts/svelte-is-here-to-stay
https://www.svelteradio.com/
https://podrocket.logrocket.com/rich-harris
https://syntax.fm/show/413/how-to-do-things-in-svelte
and unique
> [sveltekit-pod] Add content for Podcasts

- amplify.yml
- packages/deno/README.md
> [Deno] Add framework to amplify

- packages/system/src/components/landing/footer.css.ts
- packages/system/src/components/landing/footer.tsx
- packages/system/src/components/sidebar.tsx
Adds the "Deploys with Netlify" badge to the landing page footer.
> feat(landing): adds netlify badge to footer

- packages/site/src/data/deno/blogs.ts
- packages/site/src/data/deno/communities.ts
- packages/site/src/data/deno/libraries.ts
- packages/site/src/data/deno/podcasts.ts
- packages/site/src/data/search-data.ts
> [deno] Fix/542 fix updates after feedback

- packages/site/src/data/nodejs/communities.ts
Replaced image to a better quality image
Before:
After:
and unique
Closes #537
> fix: nodeconf image

- packages/site/src/data/qwik/communities.ts
- Added missing JS conferences
Closes: #548
> feat(qwik-pod): Add missing js conferences

- packages/site/src/data/qwik/blogs.ts
Add ThisDot blog page.
Closes: #549
> feat(qwik-pod): Add missing blogs

- packages/site/src/data/search-data.ts
Added a SubCategory dictionary to keep graphql customised routes and to add new subroutes for nodejs.
I added the tags that I have found in the libraries.ts file
> [node-pod] fix: customise nodejs library subsections

- packages/site/src/data/nodejs/communities.ts
I added State of Node.js to the communities section of node.
Added general list of conferences to the communities section of node
Closes #554; #555 
and unique
> [node-pod] feat: added State of Node.JS and general conferences

- packages/site/src/data/qwik/courses.ts
Closes: https://github.com/thisdot/framework.dev/issues/547
and unique
> update qwik courses from jsdrops

- packages/site/src/data/search-data.ts
Close: https://github.com/thisdot/framework.dev/issues/545
Showing only sub-categories that have data attributed to it.
and unique
> modified library sub-category for qwik

- CONTRIBUTING.md
Updates the contributing documentation with info on how to handle new framework sites.
> docs: update contributing file with info on adding a new framework

- packages/site/src/data/svelte/courses.ts
> [svelte-kit-scss] Add JS Marathon/Drops on Svelte to courses

- packages/site/src/data/svelte/communities.ts
> [svelte-kit-scss] Add meetups and conferences to framework.dev

- packages/site/src/data/graphql/communities.ts
> [graphql-pod] Add State of GraphQL and GraphQL Contributor Days To Meetups

- package.json
- packages/site/src/data/graphql/libraries.ts
> [graphql-pod] Remove Prisma From Libraries

- packages/site/src/data/graphql/libraries.ts
> [graphql-pod] Add Missing NPM Configuration to StepZen & Mulesoff

- packages/site/src/data/graphql/courses.ts
> [graphql-pod] Add Data Loaders JS Marathon To Courses

- packages/site/src/data/svelte/communities.ts
- packages/site/src/data/svelte/courses.ts
- Added missing tags on Svelte courses/communities.
and unique
Closes: #601
> feat(svelte-pod): Add missing tags

- .github/dependabot.yml
Adds dependabot.yml for auto PRs
> feat: adds dependabot config for auto PRs

- packages/system/src/components/search/results-category.tsx
- packages/system/src/components/search/search.tsx
- Revert changes on how we import the methods from Lodash.
> fix: Lodash import

- build-ignore.js
- packages/site/src/components/nav-items.tsx
- packages/site/src/pages/categories/[category]/tags/[tag].astro
- packages/system/src/components/search/search.tsx
- packages/system/src/github-util/get-contributors.ts
VITE_FRAMEWORK environment variable was missing the _ on the category pages
Added build error patches and updated ignore diff scripts
> fix: Broken Category Page Titles

- packages/site/src/data/qwik/courses.ts
- packages/site/src/data/qwik/podcasts.ts
> remove misko sarah course from podcasts

- packages/site/src/data/svelte/libraries.ts
> [svelte-kit-scss] Add https://github.com/colinhacks/zod to libraries

- packages/site/src/data/svelte/libraries.ts
> [svelte-kit-scss] Add https://daisyui.com/ to the libraries

- packages/site/src/data/solidjs/communities.ts
> Meetups is empty on framework.dev

- packages/site/src/data/solidjs/communities.ts
- Logo is not displaying on home page - https://solidjs.framework.dev/
- https://solidjs.framework.dev/categories/communities
> logo fixed

- packages/site/src/data/solidjs/communities.ts
Added conference tag in order to show conferences on the conferences' page.
Added missing conferences.
Fixes: #672 
and unique
> solid-fix: added conferences

- packages/site/src/data/angular/communities.ts
- packages/site/src/data/angular/libraries.ts
- packages/site/src/data/deno/communities.ts
- packages/site/src/data/deno/courses.ts
- packages/site/src/data/deno/podcasts.ts
- packages/site/src/data/graphql/communities.ts
- packages/site/src/data/nodejs/communities.ts
- packages/site/src/data/qwik/communities.ts
- packages/site/src/data/react/communities.ts
- packages/site/src/data/react/courses.ts
- packages/site/src/data/solidjs/blogs.ts
- packages/site/src/data/solidjs/communities.ts
- packages/site/src/data/svelte/communities.ts
- packages/site/src/data/vue/communities.ts
- packages/system/src/components/search/query-util.ts
> fixes typescript casing typos

- packages/site/src/data/solidjs/blogs.ts
- packages/site/src/data/solidjs/communities.ts
- packages/site/src/data/solidjs/podcasts.ts
> Channels
> Blogs
> Podcasts 
--- 
Closes: #694 
Closes: #695 
Closes: #696
> feat(solidjs): Fix content missing

- packages/site/src/data/qwik/tools.ts
- packages/system/src/icons/deno-icon.tsx
Resolces #717 
- Changes Qwik playground description
- Resolves ref issue
> refactor: replaces qwik playground description

- packages/site/src/data/nodejs/blogs.ts
- packages/site/src/data/nodejs/tools.ts
Fixes broken images on node site
- Wes Bos logo
- Nodist node default logo
Closes #721
> fix: adds working wes bos logo and node default for nodist

- package.json
- packages/system/src/components/cards/library-card.tsx
- packages/system/src/components/cards/resource-card.tsx
- packages/system/src/components/comparison-table/index.tsx
- packages/system/src/components/search/results-category.tsx
- packages/system/src/components/search/search.tsx
- packages/system/src/util/analytics-utils.ts
- tsconfig.json
- yarn.lock
Adds google tag custom events to library compare table actions
> chore(analytics): add custom events to compare table

- .github/workflows/thank-contributor.yml
This PR is responsible for adding the GH action for thanking contributors when their PR's are merged.
It is the same action we are using for starter.dev
closes #766
> chore: setting up thank you script

- .github/workflows/slack-notifications.yml
- .github/workflows/thank-contributor.yml
This PR resolves the following issues: 
The notification when a PR is merged shows up pretty quickly.
We want to delay the thank you notification by a couple of minutes. 
While testing the GH action earlier, we noticed that when the curl command was run to check if a user had previously contributed, it would throw an error if the user had special characters in their username.
We need to add a condition to account for that so the action doesn't fail. 
We need to make a slight modification to the messaging of the thank you script based on feedback from Dustin.
> chore: adding error handling for usernames and setting delay for action

- packages/site/src/data/react/libraries.ts
This pull request add 1 React component
and unique
> add: Mantine.dev to Component react

- packages/site/src/data/solidjs/podcasts.ts
- packages/site/src/data/svelte/podcasts.ts
Use general podcast links, not specific episodes for all framework.dev podcasts
> Use general podcast links, not specific episodes for all framework.dev podcasts
